# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3103bd7717bacbe17a1ccba4337d222a3d8c5797ba4c4c7f9ac846bb90b6466847bdacd739e86ebc71aea79f4243e715f9277525f0a144983814e2dc89194561

test:
  secret_key_base: 9fff43c90941b7e964251e737d354e49622adfd746e3560109ec24b0ddefc7b4a961eeada7eca51874de0756a66b200ad33dc5b8171956f075cb3d0a53be36fe

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
